### ISSUE TITLE
Kabanero operator install on OCP 4.2

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#245]
This is intended to be a long-lived issue for the 0.3.0 release.  Here are some things that need to happen:

- [x] Build a private registry containing the Kabanero CSV / CRD that can be used by the Kabanero install script to install Kabanero via OLM
- [x] Landing page - need to make the OKD 3.11 customizations optional, if we don't find the config map (or just remove them altogether since we are abandoning 3.11)
- [ ] The `targetNamespaces` field will need to update the OpenShift Service Mesh role (add the namespaces to the role, to tell Knative to watch them)
- [ ] The kabanero controller status update section should be updated to detect that service mesh is installed correctly (TBD what that means).
- [x] The kabanero controller status update section should be updated to reflect the version of OpenShift Serverless that is being used.  The underlying version of Knative Serving might still be interesting, but we want to make it clear that this is coming from the Serverless operator.
- [x] Appsody will be installed via OLM, so the kabanero operator code that deploys appsody needs to be removed
- [x] Che operator will be installed via OLM, so the kabanero operator code that deploys the Che operator (but not the Che CR instance and friends) needs to be removed.
- [x] kAppNav v0.1.2 needs to be used.  See #257.  The install script should continue to do this, optionally installable, at the cluster level.
- [x] Rewrite kabanero-operators.yaml to be used by the new install script #262 
- [x] Get to a singe install script #263 
- [x] Modify the uninstall script to delete CR instances etc #264

**Comment by marikaj123** [comment]
@kaczyns - Is the work for the issue on track to complete by Nov-15?

**Comment by kaczyns** [comment]
I am going to mark this complete for release-0.3.  We did not update the Service Mesh Member Role for namespaces in the `targetNamespaces` field.  This is because:
1) The serverless portion of `AppsodyApplication` is optional.  We don't know if the user wants it.
2) The member role has un-intended consequences on the routes for non-serverless deployments.

The user can decide which behavior they want, and if they want to use serverless, they can update the member role appropriately.  If they don't want serverless, no further action is required.
