### ISSUE TITLE
Ability to read private repository kabanero index

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-operator#253]
- Ability to read kabanero index from private repository or GHE
- Login with user/token with at least repository read permissions

@mtamboli 

- [x] Authentication via OAuth with Github PAT (#467)
- [x] Select the correct Secret (#468)
- [x] Download the correct release asset (#469)
- [x] Cache the result as we do for HTTPS (#470)
- [x] Document coding the Github asset name in the Kabanero CR instance (kabanero-io/docs#341)

**Comment by kaczyns** [comment]
@dacleyra @mtamboli We need to narrow the scope of what you're asking for here.  Are you asking to be able to read the kabanero-index.yaml from a **release** in a private repository or GHE?  Or from an arbitrary location/url inside a branch / tree?  The APIs we use to retrieve it would be different depending on which it is.

**Comment by stephenkinder** [comment]
So I think we need to look at this problem holistically across the set of open projects that interact with the collection.  Offering management is looking at various features related to collection hosting pain points.

**Comment by dacleyra** [comment]
At minimum, kabanero-index.yaml from a release in a private repository or GHE

**Comment by kaczyns** [comment]
The changes in #386 will make is possible to have protocol-specific syntax for:
* Stack indexes
* Pipeline zips
* Trigger zips

Each of these will start off supporting `https` but can be enhanced to support others such as Github API.  There appear to be two flavors of the Github API depending on what you want to get:
* Release assets
* Regular files from a branch (including master)

There will need to be two flavors of the Github protocol syntax in Kabanero and Stack CRDs to support both of these kinds of files.  I suggest that if we are going to start with one, we start with the release.  So the user would need to supply the repository, the release name, and the asset name.

It was suggested in #386 that we adopt the Tekton model for associating credentials with the Github requests.  The tekton model is described here: https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#basic-authentication-git

Essentially, you create a secret with an annotation that describes the server you're authenticating too.  The data in the secret has the username and password (or PAT).  You then associate the secret with a service account.  Any PipelineRuns etc that use the service account will have the secret mounted, and then the Tekton code can find the secret to use with the associated resource by inspecting the annotation.  This model fits this case well because there are lots of kinds of resources that can run and be associated with the same service account.

For Kabanero, it will always be specific pods that need to use the credentials.  Since the Kabanero controller is creating the service accounts, the user would never associate the secrets with a service account.  Rather than have the user associate the secret with a service account, the user could just associate the secret with the Kabanero CR instance.  The Kabanero controller can then in turn modify the service accounts that it uses (or the deployments that create the pods) with the secrets.  The annotation style can be preserved (using kabanero.io instead of tekton.dev) to let the pod select the correct credentials based on the server being accessed.

In addition to the Kabanero and Stack controllers being able to read these new objects and configuration, the CLI service and the Kabanero Console (landing page) must do so also.  Since these are Java applications, the implementation will be different, although the basic strategy of picking the secret based on the annotation will remain the same.

It's not clear to me whether the annotation on the secret is useful when the secret is mounted to the pod's (container's) file system.  It seems like the pod still needs to use the kube API to get the secret, to inspect its annotation and thereby pick the right directory in the file system (Based on the secret's name).  If the annotation information is somehow captured in the file system, that would be useful.

**Comment by kaczyns** [comment]
It turns out tekton has a second "explicit" way to specify credentials which is documented here:
https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#pull-request-resource

This requires the specific secret to be put in the CR instance, as well as the key within the secret that contains the credential, and in some cases the header name in the HTTP request where that value should be populated.

**Comment by kaczyns** [comment]
Things are going well with the exception of the cache - we're having some trouble caching the results when using the GitHub API URL.  See #470.  We may just leave that out for now.

**Comment by kaczyns** [comment]
470 is fixed - so closing this issue.
